### ISSUE TITLE
"Get key failed from google"

### ISSUE THREAD

**Issue by Gruffnco** [DeanCording/node-red-contrib-google-tts#2]
Just stopped working no audio out.
Error flagged "Get key failed from google"

**Comment by DeanCording** [comment]
It will be a couple of days before I can have a look at it.

**Comment by DeanCording** [comment]
Fixed in Version 1.1.1

**Comment by JuniorGamingTime** [comment]
I posted a new issue do to this being a few years ago, so could be something different
