### ISSUE TITLE
"Get key failed from google" error

### ISSUE THREAD

**Issue by JuniorGamingTime** [DeanCording/node-red-contrib-google-tts#7]
Just like the title says, I've been using this node for over a year with no issues. But now I keep getting this error. Any fix for this?

**Comment by JuniorGamingTime** [comment]
No updates on this???

**Comment by Boudewijn26** [comment]
This is very likely related to similar issues over at Home Assistant (https://github.com/home-assistant/core/issues/42911, https://github.com/home-assistant/core/issues/43801), gTTS (https://github.com/pndurette/gTTS/issues/232) and thus gTTS token. As well as in the Node world of things like google-tts (https://github.com/zlargon/google-tts/issues/33, https://github.com/zlargon/google-tts/issues/35, https://github.com/zlargon/google-tts/issues/36), where [google-translate-tts](https://github.com/ncpierson/google-translate-tts) is now a working implementation.

I hope any fixers can be helped by my [analysis of these changes](https://github.com/Boudewijn26/gTTS-token/blob/master/docs/november-2020-translate-changes.md).

**Comment by JuniorGamingTime** [comment]
@Boudewijn26 would google-translate-tts work with nodered? Or another alternative that works with nodered?

**Comment by florabtw** [comment]
I can try to repackage [google-translate-tts](https://github.com/ncpierson/google-translate-tts) for nodered, but I've never done that before. If anyone else wants to make that contribution, it would be very welcome :)

**Comment by Boudewijn26** [comment]
@JuniorGamingTime I really can't say. It already appears @ncpierson knows far better than I. My Google TTS adventures have been mostly limited to Python. I do hope someone with the relevant experience will also be able to chime in.

**Comment by florabtw** [comment]
Just added `google-translate-tts` to Node RED. You should be able to add it like you do any other node.
Here is the package for reference: https://flows.nodered.org/node/google-translate-tts

**Comment by JuniorGamingTime** [comment]
Omg thanks so much, ill get on it in a few minutes here.

**Comment by JuniorGamingTime** [comment]
So far it seems to work well. How could I change the languages? Just i changing the "en-US" to a supported Google tts language?

**Comment by JuniorGamingTime** [comment]
Only thing is that if i change the of the node in the settings, the node name stays as "text-to-speech" other languages seems to be working well too

**Comment by florabtw** [comment]
Yeah, the node properties has a "voice code" field which you can change. The supported codes are not really documented, but the list in [this file](https://github.com/ncpierson/google-translate-tts/blob/master/src/voices.js) should all be supported.

Google also has a list but I don't think *all* the codes are supported. Google frequently adds support for more languages, though: https://cloud.google.com/speech-to-text/docs/languages

**Comment by florabtw** [comment]
Whoops, I never tested changing the node name, I just assumed it would work. I'll fix that.

**Comment by freddiefujiwara** [comment]
@JuniorGamingTime hi 
https://www.npmjs.com/package/google-tts-api
Updated to solve this issue v0.0.6
Have a try

Thanks

**Comment by JuniorGamingTime** [comment]
Yeah I always look for updates daily, soo I instantly updated it. No issues and it's been working great
